services:
  - type: web
    name: inforaflow
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
